#!/bin/bash

# install build dependencies

apt-get update

apt-get install -y \
    live-build \
    gnupg2 \
    binutils \
    zstd \
    ca-certificates \
    squashfs-tools  \
    live-boot  \
    live-config  \
    live-boot-initramfs-tools \
    live-config-sysvinit \
    libburn4  \
    libisofs6  \
    libisoburn1  \
    xorriso \
    curl
    