#!/bin/bash

set -e

ARCH="amd64"
# BASECODENAME="sid" #very unstable and not supported by all ftp
BASECODENAME="sid"

BASEVERSION="12" # debian bookworm

NAME="Mango-linux"
# mirror to fetch packages from
MIRROR_URL="http://ftp.debian.org/debian/"
# indian mirror: http://mirror.cse.iitk.ac.in
# german mirror: http://ftp.de.debian.org
# MIRROR_BINARY_URL="https://repo.vanillaos.org"
MIRROR_BINARY_URL="http://ftp.debian.org/debian/"

# MIRROR_SECURITY_URL="http://deb.debian.org/debian-security"
MIRROR_SECURITY_URL="http://security.debian.org/debian-security"

# use HWE kernel and packages?
# HWE_KERNEL="yes"

# suffix for generated .iso files
OUTPUT_SUFFIX="test-1" # CHANGE THIS

# folder suffix for the package lists to use
PACKAGE_LISTS_SUFFIX="vanilla-installer"

BOOTLOADER="grub-pc"
# default is syslinux
# --bootloaders grub-legacy|grub-pc|syslinux|grub-efi|"BOOTLOADERS"
KERNEL_FLAVORS="amd64"

IMAGE_NAME="MangoLinux"



# if [ "$HWE_KERNEL" = "yes" ]; then
#     KERNEL_FLAVORS="amd64-hwe-${BASEVERSION}"
#     # KERNEL_FLAVORS="amd64-hwe"

# else
#     KERNEL_FLAVORS="amd64"
# fi


# linux packages => linux kernel packages

# stages of live-build
# - Bootstrap : retrieving package lists, installing the core packages, and configuring the initial system environment.
# - Chroot : separate directory tree that emulates the root file system of the live system. It allows the build process to make changes and modifications within this isolated environment.
# - Binary Stage : creating the binary image of the live system, such as an ISO image or a compressed file system. It includes tasks like installing additional packages, configuring the system, and creating the final image.
# - Cleanup :  Once the binary image is generated, the cleanup stage removes temporary files and cleans up the chroot environment to ensure a clean and minimal final image.

# parent-mirror-... is used for fallback

# --binary-images iso (original)
# --firmware-binary false \ > change to true for max hardware compatibility

# --firmware-chroot false \ > disable the installation of firmware packages during the chroot phase of the live system build process.
# enable if targetting max support

# change --updates false to true later
# https://wiki.debian.org/DebianRepository > local repo information

# Archive aresL non-free, main, etc > https://www.debian.org/doc/debian-policy/ch-archive.html#archive-areas

# FIRMWARE LINUX FIX: https://www.mail-archive.com/debian-live@lists.debian.org/msg18982.html

lb config noauto \
  --architectures "$ARCH"\
  --mode debian \
  --distribution "$BASECODENAME" \
  --parent-distribution "$BASECODENAME" \
  --archive-areas "main non-free contrib non-free-firmware" \
  --linux-packages "linux-image linux-headers" \
  --linux-flavours "$KERNEL_FLAVORS" \
  --bootappend-live "boot=live config username=msm user-fullname=Msm-test hostname=msm-testing timezone=Asia/Kolkata quiet splash" \
  --mirror-bootstrap "$MIRROR_URL" \
  --mirror-chroot-security "$MIRROR_SECURITY_URL" \
  --parent-mirror-chroot-security "$MIRROR_SECURITY_URL" \
  --mirror-binary-security "$MIRROR_SECURITY_URL" \
  --parent-mirror-binary-security "$MIRROR_SECURITY_URL" \
  --mirror-binary "$MIRROR_BINARY_URL" \
  --parent-mirror-binary "$MIRROR_BINARY_URL" \
  --keyring-packages debian-keyring \
  --apt-options "--yes --option Acquire::Retries=5 --option Acquire::http::Timeout=100" \
  --apt-recommends false \
  --cache-packages false \
  --uefi-secure-boot enable \
  --binary-images iso-hybrid \
  --iso-application "$NAME" \
  --iso-volume "$NAME" \
  --iso-preparer "MSM" \
  --iso-publisher "MSM Mango Linux" \
  --firmware-binary false \
  --firmware-chroot false \
  --security true \
  --updates false \
  --debootstrap-options "--exclude=pinephone-tweaks,mobile-tweaks-common,librem5-tweaks,pinetab-tweaks --include=apt-transport-https,ca-certificates,openssl" \
  --checksums md5 \
  --clean \
  --debian-installer live \
  --debian-installer-gui true \
  --memtest memtest86+ \
  --initsystem systemd \
  --bootloaders "$BOOTLOADER" \
  --image-name="$IMAGE_NAME" \
  "${@}"

  # --clean \
  # --debootstrap-options "--keyring=/usr/share/keyrings/vanilla_keyring.gpg"

NAME="Mango-linux"
VERSION="0.0.1"
CHANNEL="testing"
CODENAME="msm-testing-code-01"
  
sed -i "s/@DISTRO_NAME/$NAME/" config/hooks/live/004-set-os-info.chroot
sed -i "s/@VERSION/$VERSION/" config/hooks/live/004-set-os-info.chroot
sed -i "s/@CHANNEL/$CHANNEL/" config/hooks/live/004-set-os-info.chroot
sed -i "s/@CODENAME/$CODENAME/" config/hooks/live/004-set-os-info.chroot
sed -i "s/@BASECODENAME/$BASECODENAME/" config/hooks/live/004-set-os-info.chroot